/**
 * Rotation universe — ticker, company, sector and industry for every symbol the
 * Rotation tab tracks.
 *
 * AUTO-GENERATED from the sector-rotation app's `src/data/stocks.ts`, which was
 * itself generated from `Sector Industry.csv`. Do not hand-edit; regenerate.
 *
 * This is the single source of truth for BOTH the ticker list and the
 * classification hierarchy. The original app duplicated these — `ALL_TICKERS`
 * in the Python API and `STOCKS` in the frontend — which could silently drift.
 * Here `ALL_TICKERS` is derived, so they cannot disagree.
 *
 * 878 symbols · 11 sectors · 125 industries
 */

export interface StockInfo {
  ticker: string;
  company: string;
  sector: string;
  industry: string;
}

export const STOCKS: StockInfo[] = [
  { ticker: 'BDSX', company: 'Biodesix Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'BNAI', company: 'Brand Engagement Network Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'AMPX', company: 'Amprius Technologies Inc', sector: 'Industrials', industry: 'Electrical Equipment & Parts' },
  { ticker: 'IOT', company: 'Samsara Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'CAPR', company: 'Capricor Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'UMAC', company: 'Unusual Machines Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'BEAM', company: 'Beam Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'AVAV', company: 'AeroVironment Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'VKTX', company: 'Viking Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'RNG', company: 'RingCentral Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'NSP', company: 'Insperity Inc', sector: 'Industrials', industry: 'Staffing & Employment Services' },
  { ticker: 'EKSO', company: 'Ekso Bionics Holdings Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'PL', company: 'Planet Labs PBC', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'MRVL', company: 'Marvell Technology Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'SOC', company: 'Sable Offshore Corp', sector: 'Energy', industry: 'Oil & Gas Drilling' },
  { ticker: 'NTLA', company: 'Intellia Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'SRPT', company: 'Sarepta Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TERN', company: 'Terns Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'BA', company: 'Boeing Co', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'TTAN', company: 'ServiceTitan Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'RCAT', company: 'Red Cat Holdings Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'SNDX', company: 'Syndax Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'VOR', company: 'Vor Biopharma Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'VELO', company: 'Velo3D Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'INOD', company: 'Innodata Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'PGNY', company: 'Progyny Inc', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'ALKT', company: 'Alkami Technology Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'DDOG', company: 'Datadog Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PLTR', company: 'Palantir Technologies Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'MDB', company: 'MongoDB Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'KTOS', company: 'Kratos Defense & Security Solutions Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'CART', company: 'Maplebear Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'DOCN', company: 'DigitalOcean Holdings Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'SFM', company: 'Sprouts Farmers Market Inc', sector: 'Consumer Defensive', industry: 'Grocery Stores' },
  { ticker: 'PCVX', company: 'Vaxcyte Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'VRNS', company: 'Varonis Systems Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'SLNO', company: 'Soleno Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'ROKU', company: 'Roku Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'EPAM', company: 'EPAM Systems Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'IMNM', company: 'Immunome Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PAVM', company: 'PAVmed Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'LQDA', company: 'Liquidia Corp', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'APGE', company: 'Apogee Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'EYPT', company: 'EyePoint Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'LMND', company: 'Lemonade Inc', sector: 'Financial', industry: 'Insurance - Property & Casualty' },
  { ticker: 'CDE', company: 'Coeur Mining Inc', sector: 'Basic Materials', industry: 'Gold' },
  { ticker: 'WAL', company: 'Western Alliance Bancorp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'ACHC', company: 'Acadia Healthcare Company Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'RGLD', company: 'Royal Gold, Inc', sector: 'Basic Materials', industry: 'Gold' },
  { ticker: 'CROX', company: 'Crocs Inc', sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  { ticker: 'KR', company: 'Kroger Co', sector: 'Consumer Defensive', industry: 'Grocery Stores' },
  { ticker: 'SNOW', company: 'Snowflake Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CF', company: 'CF Industries Holdings Inc', sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  { ticker: 'PAYX', company: 'Paychex Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CNXC', company: 'Concentrix Corp', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'BR', company: 'Broadridge Financial Solutions, Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'FFIV', company: 'F5 Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'CGON', company: 'Cg Oncology Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'GWRE', company: 'Guidewire Software Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CENX', company: 'Century Aluminum Co', sector: 'Basic Materials', industry: 'Aluminum' },
  { ticker: 'BRBR', company: 'Bellring Brands Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'GLUE', company: 'Monte Rosa Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'COST', company: 'Costco Wholesale Corp', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'NOW', company: 'ServiceNow Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'WDAY', company: 'Workday Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'INTU', company: 'Intuit Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'FOXA', company: 'Fox Corporation', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'BG', company: 'Bunge Global SA', sector: 'Consumer Defensive', industry: 'Farm Products' },
  { ticker: 'RKLB', company: 'Rocket Lab Corp', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'VERA', company: 'Vera Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CCOI', company: 'Cogent Communications Holdings Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'PSTG', company: 'Everpure Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'RTX', company: 'RTX Corp', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'RCL', company: 'Royal Caribbean Group', sector: 'Consumer Cyclical', industry: 'Travel Services' },
  { ticker: 'FIS', company: 'Fidelity National Information Services, Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'BWXT', company: 'BWX Technologies Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'NET', company: 'Cloudflare Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'TGTX', company: 'TG Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TWLO', company: 'Twilio Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'EXPE', company: 'Expedia Group Inc', sector: 'Consumer Cyclical', industry: 'Travel Services' },
  { ticker: 'KMX', company: 'Carmax Inc', sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  { ticker: 'NTRA', company: 'Natera Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'ACM', company: 'AECOM', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'ELVN', company: 'Enliven Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'DFTX', company: 'Definium Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'MAN', company: 'ManpowerGroup', sector: 'Industrials', industry: 'Staffing & Employment Services' },
  { ticker: 'DOX', company: 'Amdocs Ltd', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'PPLC', company: 'PPL Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'BAH', company: 'Booz Allen Hamilton Holding Corp', sector: 'Industrials', industry: 'Consulting Services' },
  { ticker: 'CAVA', company: 'Cava Group Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'DRS', company: 'Leonardo DRS Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'EXEL', company: 'Exelixis Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'HRB', company: 'H&R Block Inc', sector: 'Consumer Cyclical', industry: 'Personal Services' },
  { ticker: 'RBRK', company: 'Rubrik Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'ADP', company: 'Automatic Data Processing Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'INDV', company: 'Indivior Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  { ticker: 'KYMR', company: 'Kymera Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'AWK', company: 'American Water Works Co. Inc', sector: 'Utilities', industry: 'Utilities - Regulated Water' },
  { ticker: 'TVTX', company: 'Travere Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'RGTI', company: 'Rigetti Computing Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'SKYT', company: 'SkyWater Technology Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'AA', company: 'Alcoa Corp', sector: 'Basic Materials', industry: 'Aluminum' },
  { ticker: 'NEM', company: 'Newmont Corp', sector: 'Basic Materials', industry: 'Gold' },
  { ticker: 'ALB', company: 'Albemarle Corp', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'IMVT', company: 'Immunovant Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TEAM', company: 'Atlassian Corporation', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'SOFI', company: 'SoFi Technologies Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'PPTA', company: 'Perpetua Resources Corp', sector: 'Basic Materials', industry: 'Other Precious Metals & Mining' },
  { ticker: 'LBRDK', company: 'Liberty Broadband Corp', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'CTRI', company: 'Centuri Holdings Inc', sector: 'Utilities', industry: 'Utilities - Regulated Gas' },
  { ticker: 'MP', company: 'MP Materials Corporation', sector: 'Basic Materials', industry: 'Other Industrial Metals & Mining' },
  { ticker: 'FOX', company: 'Fox Corporation', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'ALAB', company: 'Astera Labs Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'CBZ', company: 'Cbiz Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'SBUX', company: 'Starbucks Corp', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'QBTS', company: 'D-Wave Quantum Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'EXPD', company: 'Expeditors International Of Washington, Inc', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'MDLN', company: 'Medline Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'ZETA', company: 'Zeta Global Holdings Corp', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'BBY', company: 'Best Buy Co. Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'DELL', company: 'Dell Technologies Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'LHX', company: 'L3Harris Technologies Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'CORT', company: 'Corcept Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'HNGE', company: 'Hinge Health Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'APG', company: 'APi Group Corporation', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'PINS', company: 'Pinterest Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'CTSH', company: 'Cognizant Technology Solutions Corp', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'EXC', company: 'Exelon Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'ESTC', company: 'Elastic N.V', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'KRMN', company: 'Karman Holdings Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'ETSY', company: 'Etsy Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'DUOL', company: 'Duolingo Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'MCO', company: 'Moody\\\'s Corp', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'ZS', company: 'Zscaler Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'VRSK', company: 'Verisk Analytics Inc', sector: 'Industrials', industry: 'Consulting Services' },
  { ticker: 'CHD', company: 'Church & Dwight Co., Inc', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'DLTR', company: 'Dollar Tree Inc', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'BRO', company: 'Brown & Brown, Inc', sector: 'Financial', industry: 'Insurance Brokers' },
  { ticker: 'NDAQ', company: 'Nasdaq Inc', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'PANW', company: 'Palo Alto Networks Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'SUNB', company: 'Sunbelt Rentals Holdings Inc', sector: 'Industrials', industry: 'Rental & Leasing Services' },
  { ticker: 'LPTH', company: 'Lightpath Technologies, Inc', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'ARQT', company: 'Arcutis Biotherapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'VLTO', company: 'Veralto Corp', sector: 'Industrials', industry: 'Pollution & Treatment Controls' },
  { ticker: 'ALGN', company: 'Align Technology, Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'MPC', company: 'Marathon Petroleum Corp', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'BTSG', company: 'BrightSpring Health Services Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'TRMB', company: 'Trimble Inc', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'GIS', company: 'General Mills, Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'LLY', company: 'Lilly(Eli) & Co', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'COGT', company: 'Cogent Biosciences Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'SSNC', company: 'SS&C Technologies Holdings Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'YUM', company: 'Yum Brands Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'CLX', company: 'Clorox Co', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'KMB', company: 'Kimberly-Clark Corp', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'CL', company: 'Colgate-Palmolive Co', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'LMT', company: 'Lockheed Martin Corp', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'DTE', company: 'DTE Energy Co', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'ELF', company: 'e.l.f. Beauty Inc', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'AXON', company: 'Axon Enterprise Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'BMRN', company: 'Biomarin Pharmaceutical Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'BBIO', company: 'BridgeBio Pharma Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CHTR', company: 'Charter Communications Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'EFX', company: 'Equifax, Inc', sector: 'Industrials', industry: 'Consulting Services' },
  { ticker: 'AMGN', company: 'AMGEN Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'HUBS', company: 'HubSpot Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'SCHW', company: 'Charles Schwab Corp', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'MLYS', company: 'Mineralys Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TWST', company: 'Twist Bioscience Corp', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'XMTR', company: 'Xometry Inc', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'GDDY', company: 'Godaddy Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'LW', company: 'Lamb Weston Holdings Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'ULS', company: 'UL Solutions Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'EQH', company: 'Equitable Holdings Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'GBCI', company: 'Glacier Bancorp, Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'TGT', company: 'Target Corp', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'ZM', company: 'Zoom Communications Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'OKTA', company: 'Okta Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'EIX', company: 'Edison International', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'GH', company: 'Guardant Health Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'LUNR', company: 'Intuitive Machines Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'TNGX', company: 'Tango Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PEGA', company: 'Pegasystems Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'ICE', company: 'Intercontinental Exchange Inc', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'HIMS', company: 'Hims & Hers Health Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  { ticker: 'LDOS', company: 'Leidos Holdings Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'C', company: 'Citigroup Inc', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'ES', company: 'Eversource Energy', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'EVRG', company: 'Evergy Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'BILL', company: 'BILL Holdings Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'NXT', company: 'Nextpower Inc', sector: 'Technology', industry: 'Solar' },
  { ticker: 'APO', company: 'Apollo Global Management Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'CALM', company: 'Cal-Maine Foods, Inc', sector: 'Consumer Defensive', industry: 'Farm Products' },
  { ticker: 'ADBE', company: 'Adobe Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'ZBH', company: 'Zimmer Biomet Holdings Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'PSA', company: 'Public Storage', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'DNLI', company: 'Denali Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'WYFI', company: 'Whitefiber Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'ED', company: 'Consolidated Edison, Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'QCOM', company: 'Qualcomm, Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'ROL', company: 'Rollins, Inc', sector: 'Consumer Cyclical', industry: 'Personal Services' },
  { ticker: 'SPGI', company: 'S&P Global Inc', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'PNW', company: 'Pinnacle West Capital Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'PWR', company: 'Quanta Services, Inc', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'JPM', company: 'JPMorgan Chase & Co', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'ELV', company: 'Elevance Health Inc', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'CMS', company: 'CMS Energy Corporation', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'MTB', company: 'M & T Bank Corp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'ZION', company: 'Zions Bancorporation N.A', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'WMT', company: 'Walmart Inc', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'CDW', company: 'CDW Corp', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'AUB', company: 'Atlantic Union Bankshares Corp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'WBS', company: 'Webster Financial Corp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'DOCU', company: 'DocuSign Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'FSLY', company: 'Fastly Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CWEN', company: 'Clearway Energy Inc', sector: 'Utilities', industry: 'Utilities - Renewable' },
  { ticker: 'ASO', company: 'Academy Sports and Outdoors Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'SNPS', company: 'Synopsys, Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'LRN', company: 'Stride Inc', sector: 'Consumer Defensive', industry: 'Education & Training Services' },
  { ticker: 'INSP', company: 'Inspire Medical Systems Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'FIBK', company: 'First Interstate BancSystem Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'WELL', company: 'Welltower Inc', sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  { ticker: 'MTDR', company: 'Matador Resources Co', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'PB', company: 'Prosperity Bancshares Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'CCI', company: 'Crown Castle Inc', sector: 'Real Estate', industry: 'REIT - Specialty' },
  { ticker: 'SEI', company: 'Solaris Energy Infrastructure Inc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'ENOV', company: 'Enovis Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'IBM', company: 'International Business Machines Corp', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'NTAP', company: 'Netapp Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'VIRT', company: 'Virtu Financial Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'TOST', company: 'Toast Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'XEL', company: 'Xcel Energy, Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'BW', company: 'Babcock & Wilcox Enterprises Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'ALNY', company: 'Alnylam Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'RCUS', company: 'Arcus Biosciences Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'D', company: 'Dominion Energy Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'GD', company: 'General Dynamics Corp', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'AFL', company: 'Aflac Inc', sector: 'Financial', industry: 'Insurance - Life' },
  { ticker: 'IONQ', company: 'IonQ Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'RHI', company: 'Robert Half Inc', sector: 'Industrials', industry: 'Staffing & Employment Services' },
  { ticker: 'DG', company: 'Dollar General Corp', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'CFG', company: 'Citizens Financial Group Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'FIGR', company: 'Figure Technology Solutions Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'HALO', company: 'Halozyme Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'SRRK', company: 'Scholar Rock Holding Corp', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'FNF', company: 'Fidelity National Financial Inc', sector: 'Financial', industry: 'Insurance - Specialty' },
  { ticker: 'EXLS', company: 'ExlService Holdings Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'DUK', company: 'Duke Energy Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'WRB', company: 'W.R. Berkley Corp', sector: 'Financial', industry: 'Insurance - Property & Casualty' },
  { ticker: 'LKQ', company: 'LKQ Corp', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'VOYG', company: 'Voyager Technologies Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'CAH', company: 'Cardinal Health, Inc', sector: 'Healthcare', industry: 'Medical Distribution' },
  { ticker: 'GOOGL', company: 'Alphabet Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'IRDM', company: 'Iridium Communications Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'PSN', company: 'Parsons Corp', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'LAUR', company: 'Laureate Education Inc', sector: 'Consumer Defensive', industry: 'Education & Training Services' },
  { ticker: 'HXL', company: 'Hexcel Corp', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'DE', company: 'Deere & Co', sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  { ticker: 'VTR', company: 'Ventas Inc', sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  { ticker: 'TEM', company: 'Tempus AI Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'PFG', company: 'Principal Financial Group Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'GOOG', company: 'Alphabet Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'ADM', company: 'Archer Daniels Midland Co', sector: 'Consumer Defensive', industry: 'Farm Products' },
  { ticker: 'DYN', company: 'Dyne Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'MET', company: 'Metlife Inc', sector: 'Financial', industry: 'Insurance - Life' },
  { ticker: 'TAP', company: 'Molson Coors Beverage Company', sector: 'Consumer Defensive', industry: 'Beverages - Brewers' },
  { ticker: 'AGIO', company: 'Agios Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CTVA', company: 'Corteva Inc', sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  { ticker: 'OKE', company: 'Oneok Inc', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'CRWD', company: 'Crowdstrike Holdings Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'LNT', company: 'Alliant Energy Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'MHK', company: 'Mohawk Industries, Inc', sector: 'Consumer Cyclical', industry: 'Furnishings, Fixtures & Appliances' },
  { ticker: 'DKNG', company: 'DraftKings Inc', sector: 'Consumer Cyclical', industry: 'Gambling' },
  { ticker: 'AFRM', company: 'Affirm Holdings Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'AEP', company: 'American Electric Power Company Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'CDNS', company: 'Cadence Design Systems, Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PNFP', company: 'Pinnacle Financial Partners Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'AVGO', company: 'Broadcom Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'INTA', company: 'Intapp Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PRCT', company: 'Procept BioRobotics Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'GS', company: 'Goldman Sachs Group, Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'CRM', company: 'Salesforce Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PTCT', company: 'PTC Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'LNG', company: 'Cheniere Energy Inc', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'MDLZ', company: 'Mondelez International Inc', sector: 'Consumer Defensive', industry: 'Confectioners' },
  { ticker: 'GM', company: 'General Motors Company', sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  { ticker: 'OII', company: 'Oceaneering International, Inc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'WWW', company: 'Wolverine World Wide, Inc', sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  { ticker: 'PM', company: 'Philip Morris International Inc', sector: 'Consumer Defensive', industry: 'Tobacco' },
  { ticker: 'AEE', company: 'Ameren Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'KBR', company: 'KBR Inc', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'O', company: 'Realty Income Corp', sector: 'Real Estate', industry: 'REIT - Retail' },
  { ticker: 'IBKR', company: 'Interactive Brokers Group Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'CNC', company: 'Centene Corp', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'PZZA', company: 'Papa John\\\'s International, Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'MRNA', company: 'Moderna Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TDS', company: 'Telephone And Data Systems, Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'HIG', company: 'Hartford Insurance Group Inc.(The)', sector: 'Financial', industry: 'Insurance - Diversified' },
  { ticker: 'KVYO', company: 'Klaviyo Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'NOG', company: 'Northern Oil and Gas Inc', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'VITL', company: 'Vital Farms Inc', sector: 'Consumer Defensive', industry: 'Farm Products' },
  { ticker: 'SWK', company: 'Stanley Black & Decker Inc', sector: 'Industrials', industry: 'Tools & Accessories' },
  { ticker: 'TMUS', company: 'T-Mobile US Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'CRNX', company: 'Crinetics Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'ACAD', company: 'Acadia Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'MCD', company: 'McDonald\\\'s Corp', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'UBER', company: 'Uber Technologies Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'VRDN', company: 'Viridian Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'LOW', company: 'Lowe\\\'s Cos., Inc', sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  { ticker: 'BSY', company: 'Bentley Systems Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'OUST', company: 'Ouster Inc', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'MA', company: 'Mastercard Incorporated', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'NEE', company: 'NextEra Energy Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'VEEV', company: 'Veeva Systems Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'TTC', company: 'Toro Co', sector: 'Industrials', industry: 'Tools & Accessories' },
  { ticker: 'TRV', company: 'Travelers Companies Inc', sector: 'Financial', industry: 'Insurance - Property & Casualty' },
  { ticker: 'PEP', company: 'PepsiCo Inc', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'HL', company: 'Hecla Mining Co', sector: 'Basic Materials', industry: 'Other Precious Metals & Mining' },
  { ticker: 'ALL', company: 'Allstate Corp', sector: 'Financial', industry: 'Insurance - Property & Casualty' },
  { ticker: 'ROP', company: 'Roper Technologies Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'ADC', company: 'Agree Realty Corp', sector: 'Real Estate', industry: 'REIT - Retail' },
  { ticker: 'UPS', company: 'United Parcel Service, Inc', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'EQR', company: 'Equity Residential Properties Trust', sector: 'Real Estate', industry: 'REIT - Residential' },
  { ticker: 'TTWO', company: 'Take-Two Interactive Software, Inc', sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  { ticker: 'MS', company: 'Morgan Stanley', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'MAS', company: 'Masco Corp', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'GPC', company: 'Genuine Parts Co', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'VSNT', company: 'Versant Media Group Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'SN', company: 'SharkNinja Inc', sector: 'Consumer Cyclical', industry: 'Furnishings, Fixtures & Appliances' },
  { ticker: 'GRAL', company: 'GRAIL Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'VSAT', company: 'Viasat, Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'CZR', company: 'Caesars Entertainment Inc', sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  { ticker: 'LIF', company: 'Life360 Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'TMHC', company: 'Taylor Morrison Home Corp', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'WPC', company: 'W. P. Carey Inc', sector: 'Real Estate', industry: 'REIT - Diversified' },
  { ticker: 'UNM', company: 'Unum Group', sector: 'Financial', industry: 'Insurance - Life' },
  { ticker: 'JNJ', company: 'Johnson & Johnson', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'ENPH', company: 'Enphase Energy Inc', sector: 'Technology', industry: 'Solar' },
  { ticker: 'V', company: 'Visa Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'WM', company: 'Waste Management, Inc', sector: 'Industrials', industry: 'Waste Management' },
  { ticker: 'SJM', company: 'J.M. Smucker Co', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'OC', company: 'Owens Corning', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'HAS', company: 'Hasbro, Inc', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'OMC', company: 'Omnicom Group, Inc', sector: 'Communication Services', industry: 'Advertising Agencies' },
  { ticker: 'FISV', company: 'Fiserv, Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'FWONK', company: 'Liberty Media Corp', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'TENB', company: 'Tenable Holdings Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'CME', company: 'CME Group Inc', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'TXN', company: 'Texas Instruments Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'ALGM', company: 'Allegro Microsystems Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'AXTA', company: 'Axalta Coating Systems Ltd', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'AMT', company: 'American Tower Corp', sector: 'Real Estate', industry: 'REIT - Specialty' },
  { ticker: 'DT', company: 'Dynatrace Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'DAWN', company: 'Day One Biopharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'HCA', company: 'HCA Healthcare Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'ZTS', company: 'Zoetis Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  { ticker: 'AHR', company: 'American Healthcare REIT Inc', sector: 'Real Estate', industry: 'REIT - Healthcare Facilities' },
  { ticker: 'SYY', company: 'Sysco Corp', sector: 'Consumer Defensive', industry: 'Food Distribution' },
  { ticker: 'DVA', company: 'DaVita Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'ATO', company: 'Atmos Energy Corp', sector: 'Utilities', industry: 'Utilities - Regulated Gas' },
  { ticker: 'VRT', company: 'Vertiv Holdings Co', sector: 'Industrials', industry: 'Electrical Equipment & Parts' },
  { ticker: 'SARO', company: 'StandardAero Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'KO', company: 'Coca-Cola Co', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'TTD', company: 'Trade Desk Inc', sector: 'Communication Services', industry: 'Advertising Agencies' },
  { ticker: 'NN', company: 'NextNav Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'RYAN', company: 'Ryan Specialty Holdings Inc', sector: 'Financial', industry: 'Insurance - Specialty' },
  { ticker: 'GILD', company: 'Gilead Sciences, Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'PRIM', company: 'Primoris Services Corp', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'FTV', company: 'Fortive Corp', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'POR', company: 'Portland General Electric Co', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'RVMD', company: 'Revolution Medicines Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'BK', company: 'Bank Of New York Mellon Corp', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'WEC', company: 'WEC Energy Group Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'ETR', company: 'Entergy Corp', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'WFC', company: 'Wells Fargo & Co', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'BAC', company: 'Bank Of America Corp', sector: 'Financial', industry: 'Banks - Diversified' },
  { ticker: 'FLR', company: 'Fluor Corporation', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'FIVN', company: 'Five9 Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'MRK', company: 'Merck & Co Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'FSLR', company: 'First Solar Inc', sector: 'Technology', industry: 'Solar' },
  { ticker: 'SRE', company: 'Sempra', sector: 'Utilities', industry: 'Utilities - Diversified' },
  { ticker: 'BL', company: 'BlackLine Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CSCO', company: 'Cisco Systems, Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'HWM', company: 'Howmet Aerospace Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'DIS', company: 'Walt Disney Co', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'CBSH', company: 'Commerce Bancshares, Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'SO', company: 'Southern Company', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'CPRT', company: 'Copart, Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'TW', company: 'Tradeweb Markets Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'AXP', company: 'American Express Co', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'HD', company: 'Home Depot, Inc', sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  { ticker: 'XYZ', company: 'Block Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'PHM', company: 'PulteGroup Inc', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'IONS', company: 'Ionis Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'RSG', company: 'Republic Services, Inc', sector: 'Industrials', industry: 'Waste Management' },
  { ticker: 'COR', company: 'Cencora Inc', sector: 'Healthcare', industry: 'Medical Distribution' },
  { ticker: 'HASI', company: 'HA Sustainable Infrastructure Capital Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'VNOM', company: 'Viper Energy Inc', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'REG', company: 'Regency Centers Corporation', sector: 'Real Estate', industry: 'REIT - Retail' },
  { ticker: 'VZ', company: 'Verizon Communications Inc', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'CRWV', company: 'CoreWeave Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'KBH', company: 'KB Home', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'CSGP', company: 'Costar Group, Inc', sector: 'Real Estate', industry: 'Real Estate Services' },
  { ticker: 'W', company: 'Wayfair Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'ORCL', company: 'Oracle Corp', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'UAL', company: 'United Airlines Holdings Inc', sector: 'Industrials', industry: 'Airlines' },
  { ticker: 'FAST', company: 'Fastenal Co', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'AOS', company: 'A.O. Smith Corp', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'TRU', company: 'TransUnion', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'IT', company: 'Gartner, Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'ACLX', company: 'Arcellx Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'AVB', company: 'Avalonbay Communities Inc', sector: 'Real Estate', industry: 'REIT - Residential' },
  { ticker: 'OXY', company: 'Occidental Petroleum Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'PG', company: 'Procter & Gamble Co', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'EBAY', company: 'EBay Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'BAM', company: 'Brookfield Asset Management Ltd', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'DKS', company: 'Dicks Sporting Goods, Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'LEU', company: 'Centrus Energy Corp', sector: 'Energy', industry: 'Uranium' },
  { ticker: 'STZ', company: 'Constellation Brands Inc', sector: 'Consumer Defensive', industry: 'Beverages - Brewers' },
  { ticker: 'ISRG', company: 'Intuitive Surgical Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'BKSY', company: 'BlackSky Technology Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'MASI', company: 'Masimo Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'RARE', company: 'Ultragenyx Pharmaceutical Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TOL', company: 'Toll Brothers Inc', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'PGR', company: 'Progressive Corp', sector: 'Financial', industry: 'Insurance - Property & Casualty' },
  { ticker: 'MSFT', company: 'Microsoft Corporation', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'Z', company: 'Zillow Group Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'PCOR', company: 'Procore Technologies Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'AJG', company: 'Arthur J. Gallagher & Co', sector: 'Financial', industry: 'Insurance Brokers' },
  { ticker: 'COLB', company: 'Columbia Banking System, Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'CRBG', company: 'Corebridge Financial Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'EA', company: 'Electronic Arts, Inc', sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  { ticker: 'AKAM', company: 'Akamai Technologies Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'SHOO', company: 'Steven Madden Ltd', sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  { ticker: 'OZK', company: 'Bank OZK', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'QDEL', company: 'QuidelOrtho Corporation', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'RMBS', company: 'Rambus Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'ORLY', company: 'O\\\'Reilly Automotive, Inc', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'HON', company: 'Honeywell International Inc', sector: 'Industrials', industry: 'Conglomerates' },
  { ticker: 'UPST', company: 'Upstart Holdings Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'ABBV', company: 'Abbvie Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'SF', company: 'Stifel Financial Corp', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'RMD', company: 'Resmed Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'RVLV', company: 'Revolve Group Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'BRK-B', company: 'Berkshire Hathaway Inc', sector: 'Financial', industry: 'Insurance - Diversified' },
  { ticker: 'CC', company: 'Chemours Company', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'TSN', company: 'Tyson Foods, Inc', sector: 'Consumer Defensive', industry: 'Farm Products' },
  { ticker: 'VRTX', company: 'Vertex Pharmaceuticals, Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PRU', company: 'Prudential Financial Inc', sector: 'Financial', industry: 'Insurance - Life' },
  { ticker: 'CELH', company: 'Celsius Holdings Inc', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'PEG', company: 'Public Service Enterprise Group Inc', sector: 'Utilities', industry: 'Utilities - Regulated Electric' },
  { ticker: 'MIR', company: 'Mirion Technologies Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'COF', company: 'Capital One Financial Corp', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'NBIX', company: 'Neurocrine Biosciences, Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - Specialty & Generic' },
  { ticker: 'GE', company: 'GE Aerospace', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'CCL', company: 'Carnival Corp', sector: 'Consumer Cyclical', industry: 'Travel Services' },
  { ticker: 'HP', company: 'Helmerich & Payne, Inc', sector: 'Energy', industry: 'Oil & Gas Drilling' },
  { ticker: 'WMG', company: 'Warner Music Group Corp', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'AMTM', company: 'Amentum Holdings Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'ADSK', company: 'Autodesk Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'CIEN', company: 'CIENA Corp', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'URBN', company: 'Urban Outfitters, Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'TJX', company: 'TJX Companies, Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'FLUT', company: 'Flutter Entertainment Plc', sector: 'Consumer Cyclical', industry: 'Gambling' },
  { ticker: 'EHC', company: 'Encompass Health Corp', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'CAT', company: 'Caterpillar Inc', sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  { ticker: 'TXT', company: 'Textron Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'BMY', company: 'Bristol-Myers Squibb Co', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'BKR', company: 'Baker Hughes Co', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'ELS', company: 'Equity Lifestyle Properties Inc', sector: 'Real Estate', industry: 'REIT - Residential' },
  { ticker: 'MPLX', company: 'MPLX LP', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'CLMT', company: 'Calumet Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'ECL', company: 'Ecolab, Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'DRI', company: 'Darden Restaurants, Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'COIN', company: 'Coinbase Global Inc', sector: 'Financial', industry: 'Financial Data & Stock Exchanges' },
  { ticker: 'HSY', company: 'Hershey Company', sector: 'Consumer Defensive', industry: 'Confectioners' },
  { ticker: 'ARE', company: 'Alexandria Real Estate Equities Inc', sector: 'Real Estate', industry: 'REIT - Office' },
  { ticker: 'SHW', company: 'Sherwin-Williams Co', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'CBRE', company: 'CBRE Group Inc', sector: 'Real Estate', industry: 'Real Estate Services' },
  { ticker: 'LNC', company: 'Lincoln National Corp', sector: 'Financial', industry: 'Insurance - Life' },
  { ticker: 'GPCR', company: 'Structure Therapeutics Inc ADR', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TROW', company: 'T. Rowe Price Group Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'FORM', company: 'FormFactor Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'UNH', company: 'Unitedhealth Group Inc', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'APPN', company: 'Appian Corp', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'INCY', company: 'Incyte Corp', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CHRW', company: 'C.H. Robinson Worldwide, Inc', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'NFLX', company: 'Netflix Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'MXL', company: 'MaxLinear Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'DD', company: 'DuPont de Nemours Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'MAA', company: 'Mid-America Apartment Communities, Inc', sector: 'Real Estate', industry: 'REIT - Residential' },
  { ticker: 'TSLA', company: 'Tesla Inc', sector: 'Consumer Cyclical', industry: 'Auto Manufacturers' },
  { ticker: 'FTNT', company: 'Fortinet Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'MNST', company: 'Monster Beverage Corp', sector: 'Consumer Defensive', industry: 'Beverages - Non-Alcoholic' },
  { ticker: 'PSX', company: 'Phillips 66', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'SSRM', company: 'SSR Mining Inc', sector: 'Basic Materials', industry: 'Gold' },
  { ticker: 'CUBE', company: 'CubeSmart', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'MKC', company: 'McCormick & Co., Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'SON', company: 'Sonoco Products Co', sector: 'Consumer Cyclical', industry: 'Packaging & Containers' },
  { ticker: 'ZG', company: 'Zillow Group Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'SMCI', company: 'Super Micro Computer Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'EMR', company: 'Emerson Electric Co', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'PYPL', company: 'PayPal Holdings Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'IVZ', company: 'Invesco Ltd', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'STAA', company: 'Staar Surgical Co', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'SYF', company: 'Synchrony Financial', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'USB', company: 'U.S. Bancorp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'SCI', company: 'Service Corp. International', sector: 'Consumer Cyclical', industry: 'Personal Services' },
  { ticker: 'ALMS', company: 'Alumis Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'ABNB', company: 'Airbnb Inc', sector: 'Consumer Cyclical', industry: 'Travel Services' },
  { ticker: 'SCCO', company: 'Southern Copper Corporation', sector: 'Basic Materials', industry: 'Copper' },
  { ticker: 'AAPL', company: 'Apple Inc', sector: 'Technology', industry: 'Consumer Electronics' },
  { ticker: 'KD', company: 'Kyndryl Holdings Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'MMM', company: '3M Co', sector: 'Industrials', industry: 'Conglomerates' },
  { ticker: 'BWA', company: 'BorgWarner Inc', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'CAKE', company: 'Cheesecake Factory Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'META', company: 'Meta Platforms Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'GEV', company: 'GE Vernova Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'ATI', company: 'ATI Inc', sector: 'Industrials', industry: 'Metal Fabrication' },
  { ticker: 'KNTK', company: 'Kinetik Holdings Inc', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'FIVE', company: 'Five Below Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'CVX', company: 'Chevron Corp', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { ticker: 'ALK', company: 'Alaska Air Group Inc', sector: 'Industrials', industry: 'Airlines' },
  { ticker: 'EXR', company: 'Extra Space Storage Inc', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'EQT', company: 'EQT Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'BOX', company: 'Box Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'PAYC', company: 'Paycom Software Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'DAL', company: 'Delta Air Lines, Inc', sector: 'Industrials', industry: 'Airlines' },
  { ticker: 'ITT', company: 'ITT Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'OPCH', company: 'Option Care Health Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'TTEK', company: 'Tetra Tech, Inc', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'NCLH', company: 'Norwegian Cruise Line Holdings Ltd', sector: 'Consumer Cyclical', industry: 'Travel Services' },
  { ticker: 'SYK', company: 'Stryker Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'USFD', company: 'US Foods Holding Corp', sector: 'Consumer Defensive', industry: 'Food Distribution' },
  { ticker: 'MO', company: 'Altria Group Inc', sector: 'Consumer Defensive', industry: 'Tobacco' },
  { ticker: 'MAR', company: 'Marriott International, Inc', sector: 'Consumer Cyclical', industry: 'Lodging' },
  { ticker: 'COO', company: 'Cooper Companies, Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'DASH', company: 'DoorDash Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'ROST', company: 'Ross Stores, Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'OMF', company: 'OneMain Holdings Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'AME', company: 'Ametek Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'APA', company: 'APA Corporation', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'BLDR', company: 'Builders Firstsource Inc', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'CTAS', company: 'Cintas Corporation', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'GMED', company: 'Globus Medical Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'TSCO', company: 'Tractor Supply Co', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'MRSH', company: 'Marsh', sector: 'Financial', industry: 'Insurance Brokers' },
  { ticker: 'BDX', company: 'Becton Dickinson & Co', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'APLS', company: 'Apellis Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'DAR', company: 'Darling Ingredients Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'FITB', company: 'Fifth Third Bancorp', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'NTNX', company: 'Nutanix Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'SM', company: 'SM Energy Co', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'RJF', company: 'Raymond James Financial, Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'EMN', company: 'Eastman Chemical Co', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'NUE', company: 'Nucor Corp', sector: 'Basic Materials', industry: 'Steel' },
  { ticker: 'BIIB', company: 'Biogen Inc', sector: 'Healthcare', industry: 'Drug Manufacturers - General' },
  { ticker: 'CRK', company: 'Comstock Resources, Inc', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'PNC', company: 'PNC Financial Services Group Inc', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'XYL', company: 'Xylem Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'TREX', company: 'TREX Co., Inc', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'WLK', company: 'Westlake Corporation', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'NKE', company: 'Nike, Inc', sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  { ticker: 'VVV', company: 'Valvoline Inc', sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  { ticker: 'STEP', company: 'StepStone Group Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'AMZN', company: 'Amazon.com Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'IRM', company: 'Iron Mountain Inc', sector: 'Real Estate', industry: 'REIT - Specialty' },
  { ticker: 'SOLV', company: 'Solventum Corp', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'TPR', company: 'Tapestry Inc', sector: 'Consumer Cyclical', industry: 'Luxury Goods' },
  { ticker: 'CARG', company: 'CarGurus Inc', sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  { ticker: 'FTAI', company: 'FTAI Aviation Ltd', sector: 'Industrials', industry: 'Rental & Leasing Services' },
  { ticker: 'POWI', company: 'Power Integrations Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'PCAR', company: 'Paccar Inc', sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  { ticker: 'DINO', company: 'HF Sinclair Corp', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'CRCL', company: 'Circle Internet Group Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'DHI', company: 'D.R. Horton Inc', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'IE', company: 'Ivanhoe Electric Inc', sector: 'Basic Materials', industry: 'Copper' },
  { ticker: 'CRVS', company: 'Corvus Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PLD', company: 'Prologis Inc', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'EWTX', company: 'Edgewise Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'FROG', company: 'JFrog Ltd', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'ST', company: 'Sensata Technologies Holding Plc', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'LAZ', company: 'Lazard Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'OTIS', company: 'Otis Worldwide Corp', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'PTC', company: 'PTC Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PGY', company: 'Pagaya Technologies Ltd', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'APP', company: 'Applovin Corp', sector: 'Communication Services', industry: 'Advertising Agencies' },
  { ticker: 'NTRS', company: 'Northern Trust Corp', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'BJ', company: 'BJ\\\'s Wholesale Club Holdings Inc', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'APH', company: 'Amphenol Corp', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'MSI', company: 'Motorola Solutions Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'OLLI', company: 'Ollies Bargain Outlet Holdings Inc', sector: 'Consumer Defensive', industry: 'Discount Stores' },
  { ticker: 'STX', company: 'Seagate Technology Holdings Plc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'SATS', company: 'EchoStar Corp', sector: 'Communication Services', industry: 'Telecom Services' },
  { ticker: 'HAL', company: 'Halliburton Co', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'GFS', company: 'GlobalFoundries Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'NYT', company: 'New York Times Co', sector: 'Communication Services', industry: 'Publishing' },
  { ticker: 'TXG', company: '10x Genomics Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'CALX', company: 'Calix Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'DVN', company: 'Devon Energy Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'VNT', company: 'Vontier Corporation', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'MSTR', company: 'Strategy Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'EAT', company: 'Brinker International, Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'CPT', company: 'Camden Property Trust', sector: 'Real Estate', industry: 'REIT - Residential' },
  { ticker: 'CVNA', company: 'Carvana Co', sector: 'Consumer Cyclical', industry: 'Auto & Truck Dealerships' },
  { ticker: 'EXE', company: 'Expand Energy Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'VLO', company: 'Valero Energy Corp', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'EL', company: 'Estee Lauder Cos., Inc', sector: 'Consumer Defensive', industry: 'Household & Personal Products' },
  { ticker: 'ABT', company: 'Abbott Laboratories', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'EOG', company: 'EOG Resources, Inc', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'NCNO', company: 'Ncino Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'DAN', company: 'Dana Inc', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'AROC', company: 'Archrock Inc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'HOOD', company: 'Robinhood Markets Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'MTCH', company: 'Match Group Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'GPN', company: 'Global Payments, Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'CVS', company: 'CVS Health Corp', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'QRVO', company: 'Qorvo Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'CGNX', company: 'Cognex Corp', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'AAP', company: 'Advance Auto Parts Inc', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'RPM', company: 'RPM International, Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'ADNT', company: 'Adient plc', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'FANG', company: 'Diamondback Energy Inc', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'SWKS', company: 'Skyworks Solutions, Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'OLMA', company: 'Olema Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'ADI', company: 'Analog Devices Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'GTLB', company: 'Gitlab Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'STT', company: 'State Street Corp', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'DXYZ', company: 'Destiny Tech100 Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'WMB', company: 'Williams Cos Inc', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'MC', company: 'Moelis & Co', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'WSM', company: 'Williams-Sonoma, Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'MOS', company: 'Mosaic Company', sector: 'Basic Materials', industry: 'Agricultural Inputs' },
  { ticker: 'IAC', company: 'IAC Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'AAON', company: 'AAON Inc', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'CNK', company: 'Cinemark Holdings Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'AIG', company: 'American International Group Inc', sector: 'Financial', industry: 'Insurance - Diversified' },
  { ticker: 'RBLX', company: 'Roblox Corporation', sector: 'Communication Services', industry: 'Electronic Gaming & Multimedia' },
  { ticker: 'NVDA', company: 'NVIDIA Corp', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'FOUR', company: 'Shift4 Payments Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'WYNN', company: 'Wynn Resorts Ltd', sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  { ticker: 'CARR', company: 'Carrier Global Corp', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'LINE', company: 'Lineage Inc', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'ARMK', company: 'Aramark', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'FLY', company: 'Firefly Aerospace Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'SGI', company: 'Somnigroup International Inc', sector: 'Consumer Cyclical', industry: 'Furnishings, Fixtures & Appliances' },
  { ticker: 'HUM', company: 'Humana Inc', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'XOM', company: 'Exxon Mobil Corp', sector: 'Energy', industry: 'Oil & Gas Integrated' },
  { ticker: 'CHWY', company: 'Chewy Inc', sector: 'Consumer Cyclical', industry: 'Internet Retail' },
  { ticker: 'ITW', company: 'Illinois Tool Works, Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'SMR', company: 'NuScale Power Corporation', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'LTH', company: 'Life Time Group Holdings Inc', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'YETI', company: 'YETI Holdings Inc', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'A', company: 'Agilent Technologies Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'TPG', company: 'TPG Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'PFGC', company: 'Performance Food Group Company', sector: 'Consumer Defensive', industry: 'Food Distribution' },
  { ticker: 'CMC', company: 'Commercial Metals Co', sector: 'Basic Materials', industry: 'Steel' },
  { ticker: 'SLG', company: 'SL Green Realty Corp', sector: 'Real Estate', industry: 'REIT - Office' },
  { ticker: 'OVV', company: 'Ovintiv Inc', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'COP', company: 'Conoco Phillips', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'RAL', company: 'Ralliant Corp', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'MCHP', company: 'Microchip Technology, Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'AMAT', company: 'Applied Materials Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'PLNT', company: 'Planet Fitness Inc', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'AMD', company: 'Advanced Micro Devices Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'BX', company: 'Blackstone Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'CRH', company: 'CRH Plc', sector: 'Basic Materials', industry: 'Building Materials' },
  { ticker: 'RUN', company: 'Sunrun Inc', sector: 'Technology', industry: 'Solar' },
  { ticker: 'APD', company: 'Air Products & Chemicals Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'BALL', company: 'Ball Corp', sector: 'Consumer Cyclical', industry: 'Packaging & Containers' },
  { ticker: 'ANF', company: 'Abercrombie & Fitch Co', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'LBRT', company: 'Liberty Energy Inc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'FR', company: 'First Industrial Realty Trust, Inc', sector: 'Real Estate', industry: 'REIT - Industrial' },
  { ticker: 'MUR', company: 'Murphy Oil Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'SLM', company: 'SLM Corp', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'HLT', company: 'Hilton Worldwide Holdings Inc', sector: 'Consumer Cyclical', industry: 'Lodging' },
  { ticker: 'COHR', company: 'Coherent Corp', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'DOV', company: 'Dover Corp', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'CYTK', company: 'Cytokinetics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PAR', company: 'Par Technology Corp', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'JBL', company: 'Jabil Inc', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'LVS', company: 'Las Vegas Sands Corp', sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  { ticker: 'FDX', company: 'Fedex Corp', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'WH', company: 'Wyndham Hotels & Resorts Inc', sector: 'Consumer Cyclical', industry: 'Lodging' },
  { ticker: 'EW', company: 'Edwards Lifesciences Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'TECH', company: 'Bio-Techne Corp', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'FRPT', company: 'Freshpet Inc', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'INFQ', company: 'Infleqtion Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'ILMN', company: 'Illumina Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'NSC', company: 'Norfolk Southern Corp', sector: 'Industrials', industry: 'Railroads' },
  { ticker: 'FIG', company: 'Figma Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'NKTR', company: 'Nektar Therapeutics', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'TFC', company: 'Truist Financial Corporation', sector: 'Financial', industry: 'Banks - Regional' },
  { ticker: 'Q', company: 'Qnity Electronics Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'SLB', company: 'SLB Ltd', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'FTI', company: 'TechnipFMC plc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'DLR', company: 'Digital Realty Trust Inc', sector: 'Real Estate', industry: 'REIT - Specialty' },
  { ticker: 'PACS', company: 'PACS Group Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'AEO', company: 'American Eagle Outfitters Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'TMO', company: 'Thermo Fisher Scientific Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'U', company: 'Unity Software Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'PRKS', company: 'United Parks & Resorts Inc', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'WES', company: 'Western Midstream Partners LP', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'KKR', company: 'KKR & Co. Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'WDC', company: 'Western Digital Corp', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'INSM', company: 'Insmed Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CAI', company: 'Caris Life Sciences Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'CVI', company: 'CVR Energy Inc', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'LYV', company: 'Live Nation Entertainment Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'YOU', company: 'Clear Secure Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'GEHC', company: 'GE HealthCare Technologies Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'NVST', company: 'Envista Holdings Corp', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'FERG', company: 'Ferguson Enterprises Inc', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'LPX', company: 'Louisiana-Pacific Corp', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'CCK', company: 'Crown Holdings, Inc', sector: 'Consumer Cyclical', industry: 'Packaging & Containers' },
  { ticker: 'ALLY', company: 'Ally Financial Inc', sector: 'Financial', industry: 'Credit Services' },
  { ticker: 'AR', company: 'Antero Resources Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'LEN', company: 'Lennar Corp', sector: 'Consumer Cyclical', industry: 'Residential Construction' },
  { ticker: 'RDDT', company: 'Reddit Inc', sector: 'Communication Services', industry: 'Internet Content & Information' },
  { ticker: 'LENZ', company: 'LENZ Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'QXO', company: 'QXO Inc', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'FLEX', company: 'Flex Ltd', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'CWST', company: 'Casella Waste Systems, Inc', sector: 'Industrials', industry: 'Waste Management' },
  { ticker: 'SMTC', company: 'Semtech Corp', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'KLAC', company: 'KLA Corp', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'IQV', company: 'IQVIA Holdings Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'PLAB', company: 'Photronics, Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'METC', company: 'Ramaco Resources Inc', sector: 'Basic Materials', industry: 'Coking Coal' },
  { ticker: 'MIAX', company: 'Miami International Holdings Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'BTU', company: 'Peabody Energy Corp', sector: 'Energy', industry: 'Thermal Coal' },
  { ticker: 'HSIC', company: 'Henry Schein Inc', sector: 'Healthcare', industry: 'Medical Distribution' },
  { ticker: 'FCX', company: 'Freeport-McMoRan Inc', sector: 'Basic Materials', industry: 'Copper' },
  { ticker: 'ACMR', company: 'ACM Research Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'SPG', company: 'Simon Property Group, Inc', sector: 'Real Estate', industry: 'REIT - Retail' },
  { ticker: 'BSX', company: 'Boston Scientific Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'KRC', company: 'Kilroy Realty Corp', sector: 'Real Estate', industry: 'REIT - Office' },
  { ticker: 'RBA', company: 'RB Global Inc', sector: 'Industrials', industry: 'Specialty Business Services' },
  { ticker: 'AVT', company: 'Avnet Inc', sector: 'Technology', industry: 'Electronics & Computer Distribution' },
  { ticker: 'UNP', company: 'Union Pacific Corp', sector: 'Industrials', industry: 'Railroads' },
  { ticker: 'DGX', company: 'Quest Diagnostics, Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'RRC', company: 'Range Resources Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'DHR', company: 'Danaher Corp', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'ASTS', company: 'AST SpaceMobile Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'CBRL', company: 'Cracker Barrel Old Country Store Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'TDC', company: 'Teradata Corp', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'STLD', company: 'Steel Dynamics Inc', sector: 'Basic Materials', industry: 'Steel' },
  { ticker: 'MGM', company: 'MGM Resorts International', sector: 'Consumer Cyclical', industry: 'Resorts & Casinos' },
  { ticker: 'BRZE', company: 'Braze Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'RKT', company: 'Rocket Companies Inc', sector: 'Financial', industry: 'Mortgage Finance' },
  { ticker: 'FND', company: 'Floor & Decor Holdings Inc', sector: 'Consumer Cyclical', industry: 'Home Improvement Retail' },
  { ticker: 'DXCM', company: 'Dexcom Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'VMC', company: 'Vulcan Materials Co', sector: 'Basic Materials', industry: 'Building Materials' },
  { ticker: 'IR', company: 'Ingersoll-Rand Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'BTGO', company: 'BitGo Holdings Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'CHYM', company: 'Chime Financial Inc', sector: 'Technology', industry: 'Software - Application' },
  { ticker: 'BF-B', company: 'Brown-Forman Corp', sector: 'Consumer Defensive', industry: 'Beverages - Wineries & Distilleries' },
  { ticker: 'AAOI', company: 'Applied Optoelectronics Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'WAY', company: 'Waystar Holding Corp', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'LASR', company: 'nLIGHT Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'UEC', company: 'Uranium Energy Corp', sector: 'Energy', industry: 'Uranium' },
  { ticker: 'DECK', company: 'Deckers Outdoor Corp', sector: 'Consumer Cyclical', industry: 'Footwear & Accessories' },
  { ticker: 'TEX', company: 'Terex Corp', sector: 'Industrials', industry: 'Farm & Heavy Construction Machinery' },
  { ticker: 'CEG', company: 'Constellation Energy Corporation', sector: 'Utilities', industry: 'Utilities - Independent Power Producers' },
  { ticker: 'ANET', company: 'Arista Networks Inc', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'MU', company: 'Micron Technology Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'CNM', company: 'Core & Main Inc', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'WHR', company: 'Whirlpool Corp', sector: 'Consumer Cyclical', industry: 'Furnishings, Fixtures & Appliances' },
  { ticker: 'TRGP', company: 'Targa Resources Corp', sector: 'Energy', industry: 'Oil & Gas Midstream' },
  { ticker: 'KGS', company: 'Kodiak Gas Services Inc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'DOCS', company: 'Doximity Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'ON', company: 'ON Semiconductor Corp', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'INTC', company: 'Intel Corp', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'PARR', company: 'Par Pacific Holdings Inc', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'NRG', company: 'NRG Energy Inc', sector: 'Utilities', industry: 'Utilities - Independent Power Producers' },
  { ticker: 'BBNX', company: 'Beta Bionics Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'NE', company: 'Noble Corp Plc', sector: 'Energy', industry: 'Oil & Gas Drilling' },
  { ticker: 'IP', company: 'International Paper Co', sector: 'Consumer Cyclical', industry: 'Packaging & Containers' },
  { ticker: 'ARES', company: 'Ares Management Corp', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'RNA', company: 'Atrium Therapeutics Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'PPG', company: 'PPG Industries, Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'KEYS', company: 'Keysight Technologies Inc', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'LRCX', company: 'Lam Research Corp', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'EYE', company: 'National Vision Holdings Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'ARWR', company: 'Arrowhead Pharmaceuticals Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'IFF', company: 'International Flavors & Fragrances Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'WSC', company: 'WillScot Holdings Corp', sector: 'Industrials', industry: 'Rental & Leasing Services' },
  { ticker: 'MOH', company: 'Molina Healthcare Inc', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'SOLS', company: 'Solstice Advanced Materials Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'RVTY', company: 'Revvity Inc', sector: 'Healthcare', industry: 'Diagnostics & Research' },
  { ticker: 'CG', company: 'Carlyle Group Inc', sector: 'Financial', industry: 'Asset Management' },
  { ticker: 'VNO', company: 'Vornado Realty Trust', sector: 'Real Estate', industry: 'REIT - Office' },
  { ticker: 'AMKR', company: 'AMKOR Technology Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'FBIN', company: 'Fortune Brands Innovations Inc', sector: 'Industrials', industry: 'Building Products & Equipment' },
  { ticker: 'JBHT', company: 'J.B. Hunt Transport Services, Inc', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'CRI', company: 'Carters Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'BXP', company: 'BXP Inc', sector: 'Real Estate', industry: 'REIT - Office' },
  { ticker: 'BMNR', company: 'BitMine Immersion Technologies Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'LUV', company: 'Southwest Airlines Co', sector: 'Industrials', industry: 'Airlines' },
  { ticker: 'BROS', company: 'Dutch Bros Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'OKLO', company: 'Oklo Inc', sector: 'Utilities', industry: 'Utilities - Independent Power Producers' },
  { ticker: 'GAP', company: 'Gap, Inc', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'UUUU', company: 'Energy Fuels Inc', sector: 'Energy', industry: 'Uranium' },
  { ticker: 'SHAK', company: 'Shake Shack Inc', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'VST', company: 'Vistra Corp', sector: 'Utilities', industry: 'Utilities - Independent Power Producers' },
  { ticker: 'LGN', company: 'Legence Corp', sector: 'Industrials', industry: 'Engineering & Construction' },
  { ticker: 'LSCC', company: 'Lattice Semiconductor Corp', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'FLS', company: 'Flowserve Corp', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'CNX', company: 'CNX Resources Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'AEVA', company: 'Aeva Technologies Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'WFRD', company: 'Weatherford International plc', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'CI', company: 'Cigna Group', sector: 'Healthcare', industry: 'Healthcare Plans' },
  { ticker: 'SNDK', company: 'Sandisk Corp', sector: 'Technology', industry: 'Computer Hardware' },
  { ticker: 'GXO', company: 'GXO Logistics Inc', sector: 'Industrials', industry: 'Integrated Freight & Logistics' },
  { ticker: 'GNRC', company: 'Generac Holdings Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'BOBS', company: 'Bob\\\'s Discount Furniture Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'OLN', company: 'Olin Corp', sector: 'Basic Materials', industry: 'Chemicals' },
  { ticker: 'MOD', company: 'Modine Manufacturing Co', sector: 'Consumer Cyclical', industry: 'Auto Parts' },
  { ticker: 'BWIN', company: 'The Baldwin Insurance Group Inc', sector: 'Financial', industry: 'Insurance Brokers' },
  { ticker: 'EQPT', company: 'Equipmentshare.Com Inc', sector: 'Industrials', industry: 'Rental & Leasing Services' },
  { ticker: 'YSS', company: 'York Space Systems Inc', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { ticker: 'BRKR', company: 'Bruker Corp', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'MWH', company: 'SOLV Energy Inc', sector: 'Industrials', industry: 'Infrastructure Operations' },
  { ticker: 'FPS', company: 'Forgent Power Solutions Inc', sector: 'Industrials', industry: 'Electrical Equipment & Parts' },
  { ticker: 'HTFL', company: 'Heartflow Inc', sector: 'Healthcare', industry: 'Health Information Services' },
  { ticker: 'CMG', company: 'Chipotle Mexican Grill', sector: 'Consumer Cyclical', industry: 'Restaurants' },
  { ticker: 'PLAY', company: 'Dave & Buster\\\'s Entertainment Inc', sector: 'Communication Services', industry: 'Entertainment' },
  { ticker: 'CORZ', company: 'Core Scientific Inc', sector: 'Technology', industry: 'Software - Infrastructure' },
  { ticker: 'HUT', company: 'Hut 8 Corp', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'REZI', company: 'Resideo Technologies Inc', sector: 'Industrials', industry: 'Industrial Distribution' },
  { ticker: 'TNDM', company: 'Tandem Diabetes Care Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'WERN', company: 'Werner Enterprises, Inc', sector: 'Industrials', industry: 'Trucking' },
  { ticker: 'KNX', company: 'Knight-Swift Transportation Holdings Inc', sector: 'Industrials', industry: 'Trucking' },
  { ticker: 'FLNC', company: 'Fluence Energy Inc', sector: 'Utilities', industry: 'Utilities - Renewable' },
  { ticker: 'ESI', company: 'Element Solutions Inc', sector: 'Basic Materials', industry: 'Specialty Chemicals' },
  { ticker: 'MKSI', company: 'MKS Inc', sector: 'Technology', industry: 'Scientific & Technical Instruments' },
  { ticker: 'ODFL', company: 'Old Dominion Freight Line, Inc', sector: 'Industrials', industry: 'Trucking' },
  { ticker: 'AMN', company: 'AMN Healthcare Services Inc', sector: 'Healthcare', industry: 'Medical Care Facilities' },
  { ticker: 'GLW', company: 'Corning, Inc', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'RH', company: 'RH', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'KMT', company: 'Kennametal Inc', sector: 'Industrials', industry: 'Tools & Accessories' },
  { ticker: 'OFRM', company: 'Once Upon a Farm PBC', sector: 'Consumer Defensive', industry: 'Packaged Foods' },
  { ticker: 'DOW', company: 'Dow Inc', sector: 'Basic Materials', industry: 'Chemicals' },
  { ticker: 'BBWI', company: 'Bath & Body Works Inc', sector: 'Consumer Cyclical', industry: 'Specialty Retail' },
  { ticker: 'NESR', company: 'National Energy Services Reunited Corp', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { ticker: 'DK', company: 'Delek US Holdings Inc', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'UCTT', company: 'Ultra Clean Hldgs Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'GLXY', company: 'Galaxy Digital Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'USAR', company: 'USA Rare Earth Inc', sector: 'Basic Materials', industry: 'Other Industrial Metals & Mining' },
  { ticker: 'SYM', company: 'Symbotic Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'RIOT', company: 'Riot Platforms Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'CE', company: 'Celanese Corp', sector: 'Basic Materials', industry: 'Chemicals' },
  { ticker: 'XPO', company: 'XPO Inc', sector: 'Industrials', industry: 'Trucking' },
  { ticker: 'NNE', company: 'Nano Nuclear Energy Inc', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'WRBY', company: 'Warby Parker Inc', sector: 'Healthcare', industry: 'Medical Instruments & Supplies' },
  { ticker: 'ENTG', company: 'Entegris Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'FUN', company: 'Six Flags Entertainment Corp', sector: 'Consumer Cyclical', industry: 'Leisure' },
  { ticker: 'MTSI', company: 'MACOM Technology Solutions Holdings Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'CIFR', company: 'Cipher Digital Inc', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'VSCO', company: 'Victoria\\\'s Secret & Co', sector: 'Consumer Cyclical', industry: 'Apparel Retail' },
  { ticker: 'TER', company: 'Teradyne, Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'APLD', company: 'Applied Digital Corporation', sector: 'Technology', industry: 'Information Technology Services' },
  { ticker: 'AMSC', company: 'American Superconductor Corp', sector: 'Industrials', industry: 'Specialty Industrial Machinery' },
  { ticker: 'WULF', company: 'TeraWulf Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'PBF', company: 'PBF Energy Inc', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { ticker: 'VIAV', company: 'Viavi Solutions Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'HYMC', company: 'Hycroft Mining Holding Corporation', sector: 'Basic Materials', industry: 'Gold' },
  { ticker: 'JEF', company: 'Jefferies Financial Group Inc', sector: 'Financial', industry: 'Capital Markets' },
  { ticker: 'GPGI', company: 'GPGI Inc', sector: 'Industrials', industry: 'Metal Fabrication' },
  { ticker: 'TTMI', company: 'TTM Technologies Inc', sector: 'Technology', industry: 'Electronic Components' },
  { ticker: 'RXO', company: 'RXO Inc', sector: 'Industrials', industry: 'Trucking' },
  { ticker: 'MOVE', company: 'Movano Inc', sector: 'Healthcare', industry: 'Medical Devices' },
  { ticker: 'LITE', company: 'Lumentum Holdings Inc', sector: 'Technology', industry: 'Communication Equipment' },
  { ticker: 'AEHR', company: 'Aehr Test Systems', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'GENB', company: 'Generate Biomedicines Inc', sector: 'Healthcare', industry: 'Biotechnology' },
  { ticker: 'WOLF', company: 'Wolfspeed Inc', sector: 'Technology', industry: 'Semiconductors' },
  { ticker: 'AXTI', company: 'AXT Inc', sector: 'Technology', industry: 'Semiconductor Equipment & Materials' },
  { ticker: 'BATL', company: 'Battalion Oil Corp', sector: 'Energy', industry: 'Oil & Gas E&P' },
  { ticker: 'BE', company: 'Bloom Energy Corp', sector: 'Industrials', industry: 'Electrical Equipment & Parts' },
];

/** Every tracked symbol. Derived from STOCKS so the two can never drift apart. */
export const ALL_TICKERS: string[] = STOCKS.map((s) => s.ticker);

/** Fast lookup by symbol. */
export const STOCK_BY_TICKER: ReadonlyMap<string, StockInfo> = new Map(
  STOCKS.map((s) => [s.ticker, s]),
);

/** Distinct sector names, alphabetical. */
export const SECTORS: string[] = ['Basic Materials', 'Communication Services', 'Consumer Cyclical', 'Consumer Defensive', 'Energy', 'Financial', 'Healthcare', 'Industrials', 'Real Estate', 'Technology', 'Utilities'];
