/**
 * Golden-vector check for api/src/lib/stats.ts.
 *
 * The expected values below were generated by running the ORIGINAL MarketMetrics
 * Python implementation (`api/shared/calculations.py`) — they are not hand-written,
 * and not derived from the TypeScript. That is the whole point: these functions
 * decide which tickers appear in 97 Club (>= 0.97 on three ranks) and Leading
 * Industries (top-20% slice), and a divergent tie rule produces plausible-looking
 * but wrong membership with no error anywhere.
 *
 * This repo has no test runner by design (CLAUDE.md: validation is manual E2E), so
 * this is a zero-dependency script rather than a suite.
 *
 *   cd api && npm run build && node scripts/verify-stats.js
 *
 * Exits non-zero on any mismatch.
 */

const { percentileRank, normalizeRrg, topPercentCount } = require("../dist/lib/stats.js");

const EPSILON = 1e-12;
let failures = 0;
let checks = 0;

function approxEqual(a, b) {
  if (Number.isNaN(a) && Number.isNaN(b)) return true;
  return Math.abs(a - b) < EPSILON;
}

function check(name, actual, expected) {
  checks += 1;
  const same =
    Array.isArray(actual) &&
    actual.length === expected.length &&
    actual.every((v, i) => approxEqual(v, expected[i]));

  if (same) {
    console.log(`  ok   ${name}`);
  } else {
    failures += 1;
    console.error(`  FAIL ${name}`);
    console.error(`       expected (python): ${JSON.stringify(expected)}`);
    console.error(`       actual   (ts)    : ${JSON.stringify(actual)}`);
  }
}

console.log("\npercentileRank — golden vectors from calculations.py:_percentile_rank");

check("ascending, no ties", percentileRank([3, 1, 2]), [
  1.0, 0.3333333333333333, 0.6666666666666666,
]);

// Every value ties: all share the average of positions 0..3 -> (1.5 + 1) / 4.
check("all values tied", percentileRank([5, 5, 5, 5]), [0.625, 0.625, 0.625, 0.625]);

check("partial ties", percentileRank([1, 2, 2, 3]), [0.25, 0.625, 0.625, 1.0]);

// null sorts as -Infinity, i.e. below every real value — it is NOT dropped, so
// the returned array stays index-aligned with the input.
check("null ranks lowest", percentileRank([1.0, null, 3.0, 2.0]), [0.5, 0.25, 1.0, 0.75]);

// Documents a genuine quirk: an all-missing universe does NOT rank 0. The Python
// docstring claims "NaN gets rank 0"; the implementation disagrees and we match
// the implementation.
check("all missing -> 0.75, not 0", percentileRank([null, null]), [0.75, 0.75]);

check("negatives", percentileRank([-5, -1, -3, 0, 2]), [0.2, 0.6, 0.4, 0.8, 1.0]);

check("single element", percentileRank([42]), [1.0]);

// The case that breaks a naive port: NaN === NaN is false in JS, so NaN and null
// would land in separate tie-groups unless both are mapped to -Infinity first.
check(
  "NaN and null tie together",
  percentileRank([NaN, 2.0, 2.0, null, 1.0]),
  [0.3, 0.9, 0.9, 0.3, 0.6],
);

check(
  "realistic mixed distribution",
  percentileRank([0.5, -1.2, 3.4, 3.4, 0.0, -0.1, 7.7, 2.2, 2.2, 2.2]),
  [0.4, 0.1, 0.85, 0.85, 0.3, 0.2, 1.0, 0.6, 0.6, 0.6],
);

check("empty input", percentileRank([]), []);

console.log("\nnormalizeRrg — golden vectors from calculations.py:_normalize");

check("evenly spaced", normalizeRrg([1, 2, 3, 4, 5]), [
  85.85786437626905, 92.92893218813452, 100.0, 107.07106781186548, 114.14213562373095,
]);

// Zero variance must not divide by zero — std falls back to 1.
check("flat input (zero variance)", normalizeRrg([7, 7, 7]), [100.0, 100.0, 100.0]);

check("single element", normalizeRrg([3.5]), [100.0]);

// Confirms POPULATION std (/n). Sample std (/n-1) would widen these values.
check("skewed spread (population std)", normalizeRrg([-10, 0, 10, 50]), [
  90.12121660092787, 94.51178700051548, 98.9023574001031, 116.46463899845355,
]);

check("empty input", normalizeRrg([]), []);

console.log("\ntopPercentCount — max(1, int(len * 0.2))");

check(
  "slice sizes across lengths",
  [0, 1, 4, 5, 9, 10, 126, 878].map((n) => topPercentCount(n)),
  [1, 1, 1, 1, 1, 2, 25, 175],
);

console.log("");
if (failures > 0) {
  console.error(`${failures} of ${checks} checks FAILED — do not ship this port.\n`);
  process.exit(1);
}
console.log(`All ${checks} checks passed — TypeScript matches the Python byte for byte.\n`);
