import { app, type HttpRequest, type HttpResponseInit } from "@azure/functions";
import { upsert, listByPartition, TABLES } from "../lib/tables.js";

/**
 * Journal — the rolling lessons list.
 *
 *   GET  /api/journal-summary            latest version (+ ?history=1 for all)
 *   POST /api/journal-summary            (x-timer-secret)  { points: string[] }
 *
 * Exactly what the name says: at most TEN points, ever. A new lesson must merge
 * into or extend an existing point rather than become an eleventh (user
 * decision 2026-08-08) — a list that grows without bound is a list you stop
 * reading. The cap is enforced HERE as well as in the summariser's prompt,
 * because a model asked for "at most 10" will eventually return 11.
 *
 * Every run is stored as its own version rather than overwriting, so a lesson's
 * evolution stays visible — that history is the actual record of what you
 * learned, and silently mutating it would throw that away.
 *
 * Generated by `tools/journal-sync` on the trading desktop via the Claude CLI,
 * so no model API key is needed in Azure.
 */

const MAX_POINTS = 10;
const MAX_POINT_CHARS = 400;
const PARTITION = "v1";

interface SummaryRow {
  rowKey: string;
  pointsJson?: string;
  noteCount?: number;
  generatedAt?: string;
}

/** RowKey sorts lexicographically = chronologically; newest last. */
function versionKey(iso: string): string {
  return iso.replace(/[:.]/g, "-");
}

async function save(req: HttpRequest): Promise<HttpResponseInit> {
  const secret = req.headers.get("x-timer-secret");
  if (!process.env.TIMER_SECRET || secret !== process.env.TIMER_SECRET) {
    return { status: 401, jsonBody: { error: "Unauthorized" } };
  }

  const body = (await req.json()) as { points?: unknown; noteCount?: number };
  if (!Array.isArray(body.points)) {
    return { status: 400, jsonBody: { error: "points must be an array of strings" } };
  }

  const points = body.points
    .filter((p): p is string => typeof p === "string")
    .map((p) => p.trim().slice(0, MAX_POINT_CHARS))
    .filter(Boolean)
    .slice(0, MAX_POINTS);

  if (points.length === 0) {
    return { status: 400, jsonBody: { error: "no usable points" } };
  }

  const generatedAt = new Date().toISOString();
  await upsert(TABLES.JOURNAL_SUMMARY, PARTITION, versionKey(generatedAt), {
    pointsJson: JSON.stringify(points),
    noteCount: typeof body.noteCount === "number" ? body.noteCount : 0,
    generatedAt,
  });

  return { jsonBody: { status: "ok", points: points.length, generatedAt } };
}

function parse(row: SummaryRow): { points: string[]; noteCount: number; generatedAt: string } {
  let points: string[] = [];
  try {
    const p = JSON.parse(row.pointsJson ?? "[]");
    if (Array.isArray(p)) points = p.filter((x): x is string => typeof x === "string");
  } catch { /* a corrupt version degrades to empty rather than 500 */ }
  return { points, noteCount: row.noteCount ?? 0, generatedAt: row.generatedAt ?? "" };
}

async function read(req: HttpRequest): Promise<HttpResponseInit> {
  const rows = await listByPartition<SummaryRow>(TABLES.JOURNAL_SUMMARY, PARTITION);
  rows.sort((a, b) => a.rowKey.localeCompare(b.rowKey));

  if (rows.length === 0) {
    return { jsonBody: { points: [], noteCount: 0, generatedAt: null, versions: 0 } };
  }

  const latest = parse(rows[rows.length - 1]);
  const wantHistory = req.query.get("history") === "1";

  return {
    jsonBody: {
      ...latest,
      versions: rows.length,
      history: wantHistory ? rows.map(parse) : undefined,
    },
  };
}

async function journalSummary(req: HttpRequest): Promise<HttpResponseInit> {
  try {
    return req.method === "POST" ? await save(req) : await read(req);
  } catch (err) {
    return { status: 500, jsonBody: { error: err instanceof Error ? err.message : "Unknown error" } };
  }
}

app.http("journalSummary", {
  methods: ["GET", "POST"],
  authLevel: "anonymous",
  route: "journal-summary",
  handler: journalSummary,
});
